import type { StampDefinition } from "../types.js";

export const stampDefinitions: StampDefinition[] = [
  { slug: "fall-girl-era", name: "Fall Girl Era", emoji: "🍂", description: "Joined the cozy fall kickoff.", category: "Fall", secret: false, active: true },
  { slug: "cozy-af", name: "Cozy AF", emoji: "☕", description: "Shared maximum cozy-season energy.", category: "Fall", secret: false, active: true },
  { slug: "pics-or-it-didnt-happen", name: "Pics or It Didn't Happen", emoji: "📸", description: "Shared a seasonal photo with the crew.", category: "Fall", secret: false, active: true },
  { slug: "outside-ish", name: "Outside-ish", emoji: "🌲", description: "Shared a fall walk, outdoor moment, or touch-grass attempt.", category: "Fall", secret: false, active: true },
  { slug: "sweater-weather-survivor", name: "Sweater Weather Survivor", emoji: "🧥", description: "Shared a sweater, blanket, flannel, outfit, or weather-survival strategy.", category: "Fall", secret: false, active: true },
  { slug: "little-treat-committee", name: "Little Treat Committee", emoji: "🥐", description: "Shared a seasonal drink, snack, recipe, or little treat.", category: "Fall", secret: false, active: true },
  { slug: "spooky-bitch", name: "Spooky Bitch", emoji: "🎃", description: "Participated in Halloween Chaos.", category: "Halloween", secret: false, active: true },
  { slug: "boo-crew", name: "Boo Crew", emoji: "👻", description: "Joined a spooky group activity.", category: "Halloween", secret: false, active: true },
  { slug: "witch-please", name: "Witch, Please", emoji: "🧙‍♀️", description: "Brought some witchy chaos to the server.", category: "Halloween", secret: true, active: true },
  { slug: "pumpkin-problems", name: "Pumpkin Problems", emoji: "🎨", description: "Shared a pumpkin, craft, decoration, success, or disaster.", category: "Halloween", secret: false, active: true },
  { slug: "costume-department", name: "Costume Department", emoji: "🦸‍♀️", description: "Shared a costume, makeup look, outfit, or idea.", category: "Halloween", secret: false, active: true },
  { slug: "candy-tax-auditor", name: "Candy Tax Auditor", emoji: "🍬", description: "Participated in candy rankings, trades, opinions, or the parent tax.", category: "Halloween", secret: false, active: true },
  { slug: "goblin-mode", name: "Goblin Mode", emoji: "🧌", description: "Achievement details classified by the passport office.", category: "Halloween", secret: true, active: true },
  { slug: "stuffed-and-surviving", name: "Stuffed & Surviving", emoji: "🦃", description: "Made it through Friendsgiving festivities.", category: "Friendsgiving", secret: false, active: true },
  { slug: "i-brought-a-dish", name: "I Brought a Dish", emoji: "🥧", description: "Contributed to a Friendsgiving activity.", category: "Friendsgiving", secret: false, active: true },
  { slug: "grateful-ish", name: "Grateful-ish", emoji: "💛", description: "Shared appreciation, a small win, or community thanks.", category: "Friendsgiving", secret: false, active: true },
  { slug: "leftovers-legend", name: "Leftovers Legend", emoji: "🥡", description: "Joined a post-holiday check-in, leftovers discussion, or recovery session.", category: "Friendsgiving", secret: false, active: true },
  { slug: "left-no-crumbs", name: "Left No Crumbs", emoji: "🍽️", description: "Achievement details classified by the passport office.", category: "Friendsgiving", secret: true, active: true },
  { slug: "festive-ish", name: "Festive-ish", emoji: "✨", description: "Participated in Holiday Chaos, enthusiastically or otherwise.", category: "Holidays", secret: false, active: true },
  { slug: "secret-something", name: "Secret Something", emoji: "🎁", description: "Participated in the seasonal secret exchange.", category: "Holidays", secret: false, active: true },
  { slug: "hibernation-society", name: "Hibernation Society", emoji: "🧣", description: "Joined the winter wrap-up.", category: "Winter", secret: false, active: true },
  { slug: "roll-the-credits", name: "Roll the Credits", emoji: "🎬", description: "Joined a community movie night.", category: "Events", secret: false, active: true },
  { slug: "game-on", name: "Game On", emoji: "🎮", description: "Joined a community game night.", category: "Events", secret: false, active: true },
  { slug: "menace-to-society", name: "Menace to Society", emoji: "😈", description: "Achievement details classified by the passport office.", category: "Community", secret: true, active: true },
  { slug: "mom-supporting-moms", name: "Mom Supporting Moms", emoji: "💗", description: "Showed up with encouragement for another mom.", category: "Community", secret: false, active: true },
  { slug: "professional-yapper", name: "Professional Yapper", emoji: "💬", description: "Achievement details classified by the passport office.", category: "Community", secret: true, active: true },
  { slug: "returned-from-the-dead", name: "Returned From the Dead", emoji: "🧟", description: "Returned to the Discord after being MIA.", category: "Community", secret: true, active: true, announcement: "The rumors of their disappearance were greatly exaggerated." },
  { slug: "why-are-you-awake", name: "Why Are You Awake?", emoji: "🌙", description: "Achievement details classified by the passport office.", category: "Community", secret: true, active: true },
  { slug: "instigator", name: "Instigator", emoji: "🧨", description: "Achievement details classified by the passport office.", category: "Community", secret: true, active: true },
  { slug: "i-was-here", name: "I Was Here", emoji: "🛂", description: "Collected memories across the Seasons of Chaos.", category: "Events", secret: false, active: true }
];
